#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import os
import sys
import time
import string
import colorama
colorama.init()
import argparse
import itertools

def createWordList(chrs, min_length, max_length, output):
    """
    :param `chrs` is characters to iterate.
    :param `min_length` is minimum length of characters.
    :param `max_length` is maximum length of characters.
    :param `output` is output of wordlist file.
    """
    if min_length > max_length:
        print ("[!] Please `min_length` must smaller or same as with `max_length`")
        sys.exit()
    if os.path.exists(os.path.dirname(output)) == False:
        os.makedirs(os.path.dirname(output))
    print ('\033[1;32m[+]\033[1;31m Creating wordlist at \033[1;36m`%s`\033[1;0m...' % output)
    print ('\033[1;34m[i]\033[1;32m Starting time: \033[1;31m%s\033[1;0m' % time.strftime('%H:%M:%S'))

    output = open(output, 'w')
    for n in range(min_length, max_length + 1):
        for xs in itertools.product(chrs, repeat=n):
            chars = ''.join(xs)
            output.write("%s\n" % chars)
            sys.stdout.write('\r\033[1;36m[+]\033[1;31m saving character \033[1;36m`%s`\033[1;0m' % chars)
            sys.stdout.flush()
    output.close()
    print ('\n\033[1;34m[i]\033[1;32m End time: \033[1;31m%s\033[1;0m' % time.strftime('%H:%M:%S'))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, description='Python Wordlist Generator')
    parser.add_argument('-chr', '--chars', default=None, help='characters to iterate')
    parser.add_argument('-min', '--min_length', type=int, default=1, help='minimum length of characters')
    parser.add_argument('-max', '--max_length', type=int, default=2, help='maximum length of characters')
    parser.add_argument('-out', '--output', default='output/wordlist.txt', help='output of wordlist file.')
    args = parser.parse_args()

    if args.chars is None:
        args.chars = string.printable.replace(' \t\n\r\x0b\x0c', '')
    createWordList(args.chars, args.min_length, args.max_length, args.output)